global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['backend:8080']
        labels:
          app: 'employee-backend'
          tier: 'backend'

  - job_name: 'mysql'
    scrape_interval: 15s
    static_configs:
      - targets: ['mysql-exporter:9104']
        labels:
          app: 'employee-mysql'
          tier: 'database'

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          app: 'docker-containers'
          tier: 'infrastructure'
