apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: {{ .Values.mysql.database | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.backend.springProfile | quote }}
